### ISSUE TITLE
BPE Tokenzier geting stuck while encoding `pavement`

### ISSUE THREAD

**Issue by ua741** [greyovo/CLIP-android-demo#1]
Hello,

Thank you you creating this CLIP demo app. 

While playing around with the app, we noticed that the text tokenzier isn't working for the following text "cat on the pavement".  It looks like the bpe function is getting suck in infinite loop while trying to encoding the token 'pavement'.

**Comment by greyovo** [comment]
I think I might know what's wrong. Will fix it soon :)

**Comment by greyovo** [comment]
Should fix it now. Please pull and check
