### ISSUE TITLE
Can you upload the onnx model and released APP ?

### ISSUE THREAD

**Issue by caofx0418** [greyovo/CLIP-android-demo#5]
Can you upload the onnx model and released APP ?

clip-image-encoder-quant-int8
clip-text-encoder-quant-int8

thanks1

**Comment by greyovo** [comment]
Please see PicQuery right here https://github.com/greyovo/PicQuery

**Comment by willswordh** [comment]
> Please see PicQuery right here https://github.com/greyovo/PicQuery

@greyovo Hi great work! May I ask what does resolution of 400px mean in the speed section? does it mean 400 x 400 or 20 x 20 pixels? Thanks a lot!

**Comment by greyovo** [comment]
It means 400px * 400px.

**Comment by willswordh** [comment]
@greyovo Hi! May I ask which execution provider did you choose after you have quantize the CLIP to exported to ort model? Is it [Android Neural Networks API](https://onnxruntime.ai/docs/execution-providers/NNAPI-ExecutionProvider.html)? 
Thanks a lot!

**Comment by greyovo** [comment]
@willswordh, I just use the default provider, and I did try the NNAPI and it seems not fit well to the model.
